Section "InputClass"
	Identifier "All Mice"
	MatchIsPointer "yes"
    Driver "libinput"
    Option "AccelProfile" "flat"
    # Neutral speed for the flat pointer profile.
    Option "AccelSpeed" "0.0"
EndSection
