#!/bin/bash
set -eo pipefail
die() {
    printf '%b\n' "$1" >&2
    exit "${2-1}"
}

move() {
    from="$(realpath "$1")"
    if [[ "$from" == *"$PWD"* ]]; then
        die "${from} is already linked!"
    fi
    if [[ "$from" != "$HOME"/** ]]; then
        die "I don't move files outside of \$HOME"
    fi
    file=${from#"${HOME}"/}
    # echo "$file"
    to="${HOME}/.numdots/${file}"

    [[ ! -f "$from" ]] && die "from: $from should exist"
    [[ -f "$to" ]] && die "to: $to should not exist"

    echo "$from => $to"
    mv "$from" "$to"
    echo "    \"./$file\": \"\"," >>./list.py
    git add "$file"
}

for arg in "$@"; do
    if [[ -f "$arg" ]]; then
        (move "$arg") || true
        :
    else
        argwhich=$(which "$arg") || continue
        if [[ -f "$argwhich" ]]; then
            (move "$argwhich") || true
        fi
    fi
done
